CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  username TEXT,
  password TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER authentication BEFORE UPDATE ON users BEGIN
UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;
